resources:

  - name: ndmrepo
    type: gitRepo
    # replace dr_github with your GitHub integration name
    integration: github
    pointer:
      # replace with source code location (e.g. GitHub) where you cloned this
      # sample project.
      sourceName: ambarish2012/node-docker-mac
      branch: master

jobs:
  ## Job description:
  ## - single task
  ## - custom image to run the job
  - name: container_custom_image
    type: runSh
    steps:
      - TASK:
          name: custom_container_opts
          runtime:
            options:
              imageName: drydock/u14pytall
              imageTag: master
              pull: true
              options: --dns=4.4.4.4 --dns=8.8.8.8
          script:
            - echo "Checking runtime values"
            - docker info
            - docker ps

  - name: build_mac_node_image
    type: runSh
    steps:
      - IN: ndmrepo
      - TASK:
          name: build_mac_image
          runtime:
            container: false
          script:
            - pushd $NDMREPO_STATE
            - docker build -t mynodeapp:latest .
            - docker run -d -p 9080:8080 --name mynodeapp mynodeapp:latest
            - sleep 5
            - docker stop mynodeapp
            - docker rm mynodeapp
            - popd
