resources:

  - name: nodeRepo
    type: gitRepo
    # replace dr_github with your GitHub integration name
    integration: github
    pointer:
      # replace with source code location (e.g. GitHub) where you cloned this
      # sample project.
      sourceName: ambarish2012/node-docker-windows
      branch: master

jobs:

  - name: container_single_task
    type: runSh
    runtime:
      nodePool: custom__x86_64__WindowsServer_2016
      container: true
    steps:
      - IN: nodeRepo
      - TASK:
          name: build_image
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
          script:
            - cd %NODEREPO_PATH%
            - docker build -t mynodeapp:latest .
            - docker run -p 9080:8080 mynodeapp:latest
