resources:

  - name: ndwrepo
    type: gitRepo
    # replace dr_github with your GitHub integration name
    integration: github
    pointer:
      # replace with source code location (e.g. GitHub) where you cloned this
      # sample project.
      sourceName: ambarish2012/node-docker-windows
      branch: master

jobs:

  - name: build_node_image
    type: runSh
    runtime:
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    steps:
      - IN: ndwrepo
      - TASK:
          name: build_image
          runtime:
            container: false
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
          script:
            - pushd $env:NDWREPO_STATE
            - dir
            - docker build -t mynodeapp:latest .
            - docker run -p 9080:8080 mynodeapp:latest
            - popd
